### ISSUE TITLE
You do not have to use return statement

### ISSUE THREAD

**Issue by ahmetbcakici** [sametpalitci/yelp-clone#7]
If you will just use **return** statement inside your curly braces you also can use like that:

```
const myFunc = () => (
    {
        a:"1",
        b:"2"
    }
)   
```

https://github.com/sametpalitci/yelp-clone/blob/dff9e198f2e0353ea3d9d5ec915e1cb977d4040c/server/graphql/mutations/Comment.js#L7-L27

**Comment by sametpalitci** [comment]
Yes, sure. That's true. Thanks
